"use strict";

var PubnubMessageTypes = {
  UNKNOWN: 0,
  CHAT: 1,
  HEART: 2,
  JOIN: 3,
  LOCATION: 4,
  BROADCAST_ENDED: 5,
  INVITE_FOLLOWERS: 6,
  BROADCAST_STARTED_LOCALLY: 7,
  BROADCASTER_UPLOADED_REPLAY: 8,
  TIMESTAMP: 9,
  LOCAL_PROMPT_TO_FOLLOW_BROADCASTER: 10,
  LOCAL_PROMPT_TO_SHARE_BROADCAST: 11,
  BROADCASTER_BLOCKED_VIEWER: 12,
  SUBSCRIBER_SHARED_ON_TWITTER: 13,
  SUBSCRIBER_BLOCKED_VIEWER: 14,
  SUBSCRIBER_SHARED_ON_FACEBOOK: 15,
  SCREENSHOT: 16
};

module.exports = PubnubMessageTypes;
